# How to test the scripts?

One way is to make use of unit tests, in which a minimum input with known output is used to compare the script result.

Consider a simple input $y = [1,2,3,4]$, acquired with a sample time $\tau_0$.

The Allan variance is calculated as:

$$
\sigma(\tau)^2 = \frac{1}{2} \langle \xi^2 \rangle
$$ 

where, 
$$\xi = \overline{y}_{k+m} - \overline{y}_{k}$$

and $\overline{y}_k$ is the $y$ mean over a time $\tau = m{\cdot}\tau_0$ (cluster size) and $k$ is the overlapping factor, it is an integer from $1$ to cluster size $m$. 


## Non-overlapping Allan variance

For the input $y = [1,2,3,4]$, the cluster sizes must not exceed the limit $m \leq N/2$, where $N$ is the total array size.
The minimum $m$ value is $1$, although according to the Allan variance theory, two-sample variance, $m=2$ is the first representative variance.

Therefore, $m = [1,2]$

$$\overline{y}(m=1) = [1,2,3,4]$$
$$\overline{y}(m=2) = \left[\frac{(1+2)}{2},\frac{(3+4)}{2}\right] = [1.5, 3.5]$$
\
$$\xi(m=1) = [2-1, 3-2, 4-3] = [1,1,1] $$
$$\xi(m=2) = [3.5 - 2.5] = [2] $$
\
$$\xi^2(m=1) = [1,1,1]$$
$$\xi^2(m=2) = [4]$$
\
$$\langle \xi^2 \rangle (m=1) = 1 $$
$$\langle \xi^2 \rangle (m=2) = 4 $$
\
The Allan variance is:
$$ \sigma(\tau)^2 (m=1) = 0.5 $$
$$ \sigma(\tau)^2 (m=2) = 2 $$

We can compare this result with the library Allantools

In [1]:
import allantools
import numpy as np

y = np.array([1,2,3,4,5,6])
m = np.array([1,2])
tau0 = 1 # just an example

(taus, adev, ade, adn) = allantools.adev(y, data_type="freq", taus=m)
avar = adev**2
avar

array([0.5, 2. ])

Another example is 

$$\overline{y}(m=1) =[3,1,0,-4,5,2]$$
$$\overline{y}(m=2) = [2,-2,3.5]$$
$$\overline{y}(m=3) = [2,1.5]$$
\
$$\xi(m=1) = [-2,-1,-4,9,-3] $$
$$\xi(m=2) = [-4,5.5] $$
$$\xi(m=3) = [-0.5] $$
\
$$\xi^2(m=1) = [4,1,16,81,9]$$
$$\xi^2(m=2) = [16,30.25]$$
$$\xi^2(m=3) = [0.25]$$
\
$$\langle \xi^2 \rangle (m=1) = 22.2 $$
$$\langle \xi^2 \rangle (m=2) = 23.125 $$
$$\langle \xi^2 \rangle (m=3) = 0.25 $$
\
The Allan variance is:
$$ \sigma(\tau)^2 (m=1) = 11.1 $$
$$ \sigma(\tau)^2 (m=2) = 11.5625 $$
$$ \sigma(\tau)^2 (m=3) = 0.125 $$

In [27]:
y = np.array([3,1,0,-4,5,2])
m = np.array([1,2,3])
tau0 = 1 # just an example

(taus, adev, ade, adn) = allantools.adev(y, data_type="freq", taus=m)
avar = adev**2
avar

array([11.1   , 11.5625])

## Overlapping Allan variance

The ramp input result the same output for both calculations. It makes sense, since the slope is fixed and there is no random signal around it.
 

In [2]:
y = np.array([1,2,3,4,5,6])
m = np.array([1,2])
tau0 = 1 # just an example

(taus, adev, ade, adn) = allantools.oadev(y, data_type="freq", taus=m)
avar = adev**2
avar

array([0.5, 2. ])

The random input is not the same, the second value is 11.5625 when not overlapping and when overlapping 7.7083.

In [3]:
y = np.array([3,1,0,-4,5,2])
m = np.array([1,2,3])
tau0 = 1 # just an example

(taus, adev, ade, adn) = allantools.oadev(y, data_type="freq", taus=m)
avar = adev**2
avar

array([11.1       ,  7.70833333])

$$\overline{y}(m=1) =[3,1,0,-4,5,2]$$
$$\overline{y}(m=2) = [2, 0.5, -2 0,5, 3.5]$$
$$\overline{y}(m=3) = [\frac{4}{3}, -1 ,\frac{1}{3},1]$$
\
$$\xi(m=1) = [-2,-1,-4,9,-3] $$
$$\xi(m=2) = [-4,0,5.5] $$
$$\xi(m=3) = [-\frac{1}{3}] $$
\
$$\xi^2(m=1) = [4,1,16,81,9]$$
$$\xi^2(m=2) = [16,0,30.25]$$
$$\xi^2(m=3) = [\frac{1}{9}]$$
\
$$\langle \xi^2 \rangle (m=1) = 22.2 $$
$$\langle \xi^2 \rangle (m=2) = 15.4166 $$
$$\langle \xi^2 \rangle (m=3) = 0.1111 $$
\
The Allan variance is:
$$ \sigma(\tau)^2 (m=1) = 11.1 $$
$$ \sigma(\tau)^2 (m=2) = 7.7083$$
$$ \sigma(\tau)^2 (m=3) = 0.0556 $$